/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demolib_DemoLib */

#ifndef _Included_demolib_DemoLib
#define _Included_demolib_DemoLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demolib_DemoLib
 * Method:    getToken
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_demolib_DemoLib_getToken
  (JNIEnv *, jobject, jlong);

/*
 * Class:     demolib_DemoLib
 * Method:    getMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demolib_DemoLib_getMessage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     demolib_DemoLib
 * Method:    getMessageQuoted
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demolib_DemoLib_getMessageQuoted
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
