/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DemoLib */

#ifndef _Included_DemoLib
#define _Included_DemoLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DemoLib
 * Method:    getToken
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_DemoLib_getToken
  (JNIEnv *, jobject, jlong);

/*
 * Class:     DemoLib
 * Method:    getMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DemoLib_getMessage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     DemoLib
 * Method:    getMessageQuoted
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DemoLib_getMessageQuoted
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
